export const COMMON_LABELS: Record<string, string> = {
  APPROPRIATE_RESPONSE: "답변 적합성",
  LOGICAL_FLOW: "논리적 구성",
  KEY_TERMS: "핵심 용어 활용",
  CONSISTENCY: "답변 일관성",
  GRAMMATICAL_ERRORS: "문법 정확성",
  TEAMWORK: "협업 능력",
  COMMUNICATION: "의사소통 능력",
  PROBLEM_SOLVING: "문제 해결 능력",
  ACCOUNTABILITY: "책임 의식",
  GROWTH_MINDSET: "성장 의지",
  STUTTER: "유창성",
  PRONUNCIATION: "발음 명확성",
  WPM: "말하기 속도",
};

export const TECHNICAL_CRITERIA = [
  "APPROPRIATE_RESPONSE",
  "LOGICAL_FLOW",
  "KEY_TERMS",
  "CONSISTENCY",
  "GRAMMATICAL_ERRORS",
];

export const PERSONAL_CRITERIA = [
  "TEAMWORK",
  "COMMUNICATION",
  "PROBLEM_SOLVING",
  "ACCOUNTABILITY",
  "GROWTH_MINDSET",
];

export const VOICE_CRITERIA = ["STUTTER", "PRONUNCIATION", "WPM"];

export const EVALUATION_CRITERIA: Record<string, string[]> = {
  "TECHNICAL/CHAT": TECHNICAL_CRITERIA,
  "TECHNICAL/VOICE": [...TECHNICAL_CRITERIA, ...VOICE_CRITERIA],
  "PERSONAL/CHAT": PERSONAL_CRITERIA,
  "PERSONAL/VOICE": [...PERSONAL_CRITERIA, ...VOICE_CRITERIA],
};
