import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import ErrorBoundary from "@/components/error/error-boundary";

const pretendard = localFont({
  src: [
    { path: "./fonts/Pretendard-Thin.woff2", weight: "100" },
    { path: "./fonts/Pretendard-ExtraLight.woff2", weight: "200" },
    { path: "./fonts/Pretendard-Light.woff2", weight: "300" },
    { path: "./fonts/Pretendard-Regular.woff2", weight: "400" },
    { path: "./fonts/Pretendard-Medium.woff2", weight: "500" },
    { path: "./fonts/Pretendard-SemiBold.woff2", weight: "600" },
    { path: "./fonts/Pretendard-Bold.woff2", weight: "700" },
    { path: "./fonts/Pretendard-ExtraBold.woff2", weight: "800" },
    { path: "./fonts/Pretendard-Black.woff2", weight: "900" },
  ],
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Interview King Dev Kim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
        <ErrorBoundary>{children}</ErrorBoundary>
      </body>
    </html>
  );
}
